### PR TITLE
Data Module Cleanup

### PR DESCRIPTION
**Pull request by conorsim**
- Code styling for `data` module
- Ability to create and init LDF with `dataset_name` only
- Remove unnecessary requirements 
- Remove deprecated files

### CODE REVIEW

**Comment by conorsim** [comment]
Also added export to JSON method

**Comment by conorsim** [comment]
Support for JSON loader has also been added

**Review by kozlov721 — APPROVED** [review]
LGTM

**Review by klemen1999 — APPROVED** [review]
LGTM

**Pull request merged**
