### PR TITLE
Bug Fix: Filtering Issue & Mosaic Transformation Logic Improvement

### PR DESCRIPTION
**Pull request by JSabadin**
# Bug Fix: Filtering Issue & Mosaic Transformation Logic Improvement

## Overview

This pull request addresses a bug in the filtering process for batch transformations and includes a revision of the logic for mosaic transformations. 

### Key Changes:
- **Bug Fix:** Resolved an issue where filtering in batch transformations was not functioning as expected.
- **Mosaic Logic Update:** Revised the mosaic transformation logic.

Visual appearance of the new mosaic.
image

### CODE REVIEW

**Review by klemen1999 — APPROVED** [review]

**Comment by JSabadin** [comment]
Please do not merge this yet. There is a issue at [this location](https://github.com/luxonis/luxonis-ml/blob/main/luxonis_ml/data/loaders/luxonis_loader.py#L137) that's causing the loading process to fail. I will investigate it further. It seems to be related to the indices. I was using only two images in the dataset during testing.

**Review by klemen1999 — APPROVED** [review]
LGTM thanks

**Comment by JSabadin** [comment]
Not ready to be merged yet. I'm working on the last issue.

**Review by kozlov721 — APPROVED** [review]
LGTM

**Comment by JSabadin** [comment]
Fixed the issue where cropping was not aligned properly. Now, more information is preserved from the image.

image

**Pull request merged**
